project:
  type: website

website:
  title: "ISSS608-VAA_Project"
  navbar:
    left:
      - href: Proposal/Proposal.qmd
        text: Proposal
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

