project:
  type: website

website:
  title: "ISSS608-VAA_Project"
  back-to-top-navigation: true
  navbar:
    pinned: true
    left:
      - href: Proposal/Proposal.qmd
        text: Proposal
    right:
      - href: index.qmd#top
        text: Home
      - href: index.qmd#intro
        text: Introduction
      - href: index.qmd#figures
        text: At a Glance
      - href: index.qmd#storyboard
        text: Our Works
  page-footer: 
    left: "some team name" 
    right: 
      - icon: github

format:
  html:
    theme: [cosmo, theme-styles.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: false
    grid: 
      content-mode: auto 

editor: visual

