project:
  type: website

website:
  title: "ISSS608 VAA - Project Group 3"
  back-to-top-navigation: true
  navbar:
    pinned: true
    right:
      - href: index.qmd#top
        text: Home
      - href: index.qmd#intro
        text: Introduction
      - href: index.qmd#figures
        text: At a Glance
      - href: Poster/Poster.qmd
        text: Poster
      - href: Shinyapp/Shinyapp.qmd
        text: Shiny APP
      - href: User_Manual/User_Manual.qmd
        text: User Manual
      - href: index.qmd#storyboard
        text: Our Works
  page-footer: 
    left: "ISSS608 VAA Project Group 3" 
    right: 
      - icon: github

format:
  html:
    theme: [cosmo, theme-styles.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: false
    grid: 
      content-mode: auto 

editor: visual

