project:
  type: website

website:
  title: "ISSS608-VAA_Project"
  navbar:
    pinned: true
    left:
      - href: Proposal/Proposal.qmd
        text: Proposal
    right:
      - href: index.qmd#banner
        text: Home
      - href: index.qmd#intro
        text: Introduction
      - href: index.qmd#sec-section-3
        text: Section 3
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: false
    grid: 
      content-mode: auto 

editor: visual

