---
page-layout: custom

listing: 
  id: sample-listings
  contents: 
    - "Proposal/Proposal.qmd"
    - "Shinyapp/Shinyapp.qmd"
    - "Poster/Poster.qmd"
  type: grid
  
section-titles: false
---

#  {#top}

#  {#banner .block}

::: block
<h1>Be Weatherwise <br> or Otherwise!</h1>

How well do we understand our climate in Singapore?

Should we be expecting more rain or shine? Let's find out!

<br>

<a href="https://www.nccs.gov.sg/singapores-climate-action/impact-of-climate-change-in-singapore/"><button>Find out more</button></a>
:::

#  {#intro .block}

::: block
<h1>Introduction</h1>

some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff

some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff

some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff some intro stuff
:::

#  {#figures .block}

::: block
<h1>At a Glance</h1>
:::

::: grid_block
::: {.col-xs-6 .col-md-4}
<h2>88</h2>

ml of rain fell in the year of 2023
:::

::: {.col-xs-6 .col-md-4}
<h2>37</h2>

degree celsius recorded for month of March
:::

::: {.col-xs-6 .col-md-4}
<h2>25</h2>

km/hr average wind speed
:::
:::

#  {#headline .block}

::: block
<h1>2023 was Singapore's 4th hottest year on record</h1>

Nearly 20 temperature-related records in Singapore were matched or broken. This included the highest daily temperature of 37 deg C recorded on May 13, 2023, in Ang Mo Kio, which tied with that recorded in Tengah in 1983.

With a mean temperature of 29.5 deg C, May 2023 matched March 1998 for the warmest month on record.

[Source](https://www.straitstimes.com/singapore/environment/2023-was-singapore-s-4th-hottest-year-on-record-tying-with-1997-and-2015#:~:text=Nearly%2020%20temperature%2Drelated%20records,the%20warmest%20month%20on%20record.)
:::

#  {#storyboard .block}

::: block
<h1>Our Works</h1>

<br>
:::

::: {#sample-listings}
:::
