---
title: "Explanatory models"
description: "How much of Dengue is explained by Climate?"
date: "17-Mar-2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

## Linear Regression

```{r}
pacman::p_load(
  tidyverse,
  fable,
  tsibble,
  feasts,
  patchwork,
  plotly,
  lubridate,
  caret,
  performance,
  ggstatsplot,
  qqplotr,
  tsibbledata
)
```

```{r}
df <- read_csv("data/dengue_climate_joined_by_week_transformed_diff.csv")
```

```{r}
mdl <- lm(Cases ~ avg_temp, data = df)
```

### Model Construct

```{r}
i <- c("avg_temp","tot_rainfall","avg_wind")
j <- ""
for (v in i) {
  if (j == "") {
    j <- v
  } else {
    j <- paste0(j,"+",v)
  }
}

mdl <- lm(as.formula(paste0("Cases ~ ",j)), data=df)
```

```{r}
summary(mdl)
```

### Model coeff plot

```{r}
ggcoefstats(mdl, 
            output = "plot")
```

### Model Metrics

```{r}
mdl %>% broom::tidy()
```

```{r}
summ <- summary(mdl)

summ$adj.r.squared
```

```{r}
summ$fstatistic[[1]]
```

### Model AVP

```{r}
df_a <- data.frame(Date=df$Date, Cases=mdl$fitted.values, Type="Fitted")
df_b <- data.frame(Date=df$Date, Cases=df$Cases, Type="Observed")

df_c <- dplyr::bind_rows(df_a, df_b)

ggplot(data = df_c) +
    geom_line(aes(x = Date, y = Cases, colour = Type)) +
    ggtitle("Observed vs Fitted")
```

### Model Diagnostics

```{r}
plots <- plot(check_model(mdl, panel = FALSE))
```

```{r}
plots[[6]]
```

```{r}
df_tbl <- df %>% as_tsibble(index = Date) %>% fill_gaps(.full = TRUE) %>% fill(Cases)

library(patchwork)

first_var <- TRUE
for (v in i) {
  if (first_var == TRUE) {
    p <- eval(parse(text = paste0("df_tbl %>% autoplot(",v,")")))
    first_var <- FALSE
  } else {
    p <- p / eval(parse(text = paste0("df_tbl %>% autoplot(",v,")")))
  }
}

p
```

```{r}
p1 <- df_tbl %>% autoplot(Cases)
p2 <- df_tbl %>% autoplot(avg_temp)
```

```{r}
p1 / p2
```

## Time Series Linear Regression

```{r}
# Convert the tibble dataframe to a tsibble dataframe
tslm_ts <-  df %>% dplyr::select(-c("Year", "WkNo"))
tslm_tbl <- tslm_ts %>% as_tsibble(index = Date) %>% fill_gaps(.full = TRUE) %>% fill(colnames(tslm_ts))
tslm_slice <- tslm_tbl
```

### Model Construct

```{r}
v = "Cases"
j = "log_tot_rainfall + log_avg_temp + log_avg_wind"
tslm_mdl <- tslm_slice %>%
          model(TSLM(as.formula(paste0(v," ~ ",j))))

report(tslm_mdl)
```

### Model Metrics

```{r}
tslm_mdl %>%
  accuracy()
```

### Model Residuals

```{r}
gg_tsresiduals(tslm_mdl)
```

### Model Coeff plot

```{r}
ggcoefstats(tslm_mdl %>% tidy(), 
            output = "plot")
```

```{r}
tslm_mdl %>% tidy()
```

### Model AVP

```{r}
var_fitted <- fitted(tslm_mdl)[,2:3] %>% 
  as_tibble() %>% 
  rename(Cases=.fitted)

var_fitted$Type <- "Fit"

tslm_slice$Type <- "Observed"

var_avp <- dplyr::bind_rows(var_fitted, tslm_slice)


ggplot(data = var_avp) +
  geom_line(aes(x = Date, y = Cases, colour = Type)) +
  ggtitle("Observed vs Fitted")
```
