---
title: "Take-home_Ex04_ts-regression"
---

```{r}
pacman::p_load(tidyverse, tsibbledata, fable, feasts, tsibble, ggstatsplot, performance)

```

```{r}
dengue_weather_wk_2014_tf <- read_csv("data/dengue_climate_joined_by_week_transformed_diff.csv")

```

The dataframe needs to be converted to a tsibble object before running TSLM model.

```{r}
# Create a date column which will be used to convert to a yearweek object in the next step

dengue_weather_wk_2014_tf <- dengue_weather_wk_2014_tf %>%
  mutate('Date' = make_date(year = Year) + weeks(WkNo))

```

```{r}
# Convert the tibble dataframe to a tsibble dataframe

dengue_weather_tsreg <- dengue_weather_wk_2014_tf %>%
  mutate(Week = yearweek(Date)) %>%
  as_tsibble(index = Week) %>%
  fill_gaps(.full = TRUE)

```

```{r}
ts_log_m1 <- dengue_weather_tsreg %>%
  model(TSLM(log_cases ~ log_tot_rainfall +
                  log_avg_mean_temp + 
                  log_max_temp +
                  log_min_temp +
                  log_avg_wind +
                  log_max_wind))

report(ts_log_m1)

```

```{r}
gg_tsresiduals(ts_log_m1)

```

```{r}
augment(ts_log_m1) %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_point() +
  labs(title = "Relationship between residuals and fitted values.",
       subtitle = "if a relationship exists, then response variable may require transformation.",
       y = "Residuals", x = "Fitted") +
  theme_light()

```

```{r}
ggcoefstats(ts_log_m1 %>% tidy(), 
            output = "plot")

```

```{r}
ts_log_m1 %>% tidy()
```

```{r}
var_fitted <- fitted(ts_log_m1)[,2:3] %>% 
  as_tibble() #%>% 
  #rename(Cases=.fitted)

var_fitted$Type <- "Fit"

dengue_weather_tsreg$Type <- "Observed"

var_avp <- dplyr::bind_rows(var_fitted, dengue_weather_tsreg)


ggplot(data = var_avp) +
  geom_line(aes(x = Week, y = Cases, colour = Type)) +
  ggtitle("Observed vs Fitted")

```
