---
title: "Data Import and Preparations"
---

```{r}
pacman::p_load(
  data.table,
  dplyr
)
```

# Climate

```{r}
stations = c(
  "paya lebar" = "06",
  "tengah" = "23",
  "changi" = "24",
  "seletar" = "25",
  "tai seng" = "43",
  "jurong west" = "44",
  "ang mo kio" = "109",
  "clementi" = "50",
  "admiralty" = "104",
  "sentosa" = "60",
  "pulau ubin" = "106",
  "east coast parkway" = "107",
  "marina barrage" = "108",
  "newton" = "111",
  "tuas south" = "115",
  "pasir panjang" = "116",
  "jurong island" = "117",
  "choa chu kang south" = "121"
)

col_names = c(
  "Station" = "Station",
  "Year" = "Year",
  "Month" = "Month",
  "Daily Rainfall Total (mm)" = "daily_rainfall",
  "Highest 30 Min Rainfall (mm)" = "highest_30m_rainfall",
  "Highest 30 min Rainfall (mm)" = "highest_30m_rainfall",
  "Highest 60 Min Rainfall (mm)" = "highest_60m_rainfall",
  "Highest 60 min Rainfall (mm)" = "highest_60m_rainfall",
  "Highest 120 Min Rainfall (mm)" = "highest_120m_rainfall",
  "Highest 120 min Rainfall (mm)" = "highest_120m_rainfall",
  "Mean Temperature (°C)" = "mean_temp",
  "Mean Temperature (°C)" = "mean_temp",
  "Mean Temperature (Â°C)" = "mean_temp",
  "Maximum Temperature (°C)" = "max_temp",
  "Maximum Temperature (°C)" = "max_temp",
  "Maximum Temperature (Â°C)" = "max_temp",
  "Minimum Temperature (°C)" = "min_temp",
  "Minimum Temperature (°C)" = "min_temp",
  "Minimum Temperature (Â°C)" = "min_temp",
  "Mean Wind Speed (km/h)" = "mean_wind",
  "Max Wind Speed (km/h)" = "max_wind"
)
```

```{r}
#| eval: false
#| message: false
#| error: false

pad_zero <- function(num) {
  if (num < 10) {
    return (paste0("0", as.character(num)))
  } else {
    return (as.character(num))
  }
}

clean_names <- function(df, col_names) {

  for (n in names(col_names)) {
    names(df)[names(df) == n] <- col_names[[n]]
  }
  
  return (df)
}

df <- data.table()

for (station in stations) {
  for (y in 3:23) {
    for (m in 1:12) {
      year <- pad_zero(y)
      month <- pad_zero(m)
      tryCatch(
        {
          joining_df <- data.table::fread(paste0(
          "http://www.weather.gov.sg/files/dailydata/DAILYDATA_S",
          station,
          "_20",
          year,
          month,
          ".csv"),
          encoding = "Latin-1")
          
          joining_df <- clean_names(joining_df, col_names)
          
          df <- rbindlist(list(df, joining_df), use.names=TRUE, fill=TRUE)
        }, error = function(e) {
          print(e)
        }
      )
    }
  }
}
```

```{r}
fwrite(df, "data/clean_climate_data.csv")
```

# Dengue

```{r}
files = list.files(
  path = "data/dengue/",
  pattern = ".*csv$",
  ignore.case = F,
  full.names = T
)

dengue = lapply(files, data.table::fread, encoding = "Latin-1")
dengue = dplyr::bind_rows(dengue)
dengue <- as.data.frame(dengue)
```

```{r}
colnames(dengue) <- c(
  "num_cases",
  "street_address",
  "lat",
  "lon",
  "cluster_num",
  "recent_cases_in_cluster",
  "total_cases_in_cluster",
  "date",
  "month"
)
```

```{r}
dengue$year <- substr(dengue$date, 1, 2)
```

```{r}
fwrite(dengue, "data/clean_dengue_data.csv")
```
